### ISSUE TITLE
POST /login-by-email

### ISSUE THREAD

**Issue by dsernst** [liquidvote/liquid-api#10]
# POST /login-by-email

Hit this endpoint to begin authentication.

Expects:

```
{
  email: String, email regex, <1 - 200 characters>
}
```

Response:

```
{
  status: 201,
  message: "An email has been sent with further instructions."
}
```

---------------

When they hit this endpoint, a new row will be created in the `sessions` collection.

Users can use this to authenticate whether they've already signed up or not. In either case, they'll receive an email with a hashed link to activate their session. As long as we get their email, we can follow up with them later.

It makes for a very simple form so they can begin the signup process as quickly as possible. We can collect their [other signup info](https://github.com/Crowdocracy/liquid-api/issues/8) next.

----------------

## TODO

- [x] Accept the initial request `POST /login-by-email`
- [x] Add to DB if they're new.
- [x] Send Welcome Email if they're new.
- [x] Send an email with their hashed link to authenticate
- [x] Accept the followup request to authenticate `GET /session/[session_uid]`

**Comment by dsernst** [comment]
(This implements the [design decision to use passwordless authentication](https://github.com/Crowdocracy/liquid-api/issues/6).)

**Comment by jaredscheib** [comment]
I ratify this :)

**Comment by dsernst** [comment]
Enough of this is done by [`083e3e0`](https://github.com/liquidvote/liquid-api/blob/083e3e004013390283c54385ff63ec28a88eab8f/login-by-email.js) that we could proceed with a front-end login page: https://github.com/liquidvote/liquid-ios/issues/7

**Comment by dsernst** [comment]
https://github.com/liquidvote/liquid-api/commit/9b8cbfaf19a5f8b058ed698cd39db7a800bdd2d3 finishes this.
